CLIENT_DIR=../client
COMMENTS_DIR=../comments
EVENT_BUS_DIR=../event-bus
MODERATION_DIR=../moderation
POSTS_DIR=../posts
QUERY_DIR=../query
NODE_EXEC=npm start
REACT_EXEC=npm run dev 

run_client:
	cd ${CLIENT_DIR} && ${REACT_EXEC} 
run_comments:
	cd ${COMMENTS_DIR} && ${NODE_EXEC}; 
run_event_bus:
	cd ${EVENT_BUS_DIR} && ${NODE_EXEC}; 
run_mod:
	cd ${MODERATION_DIR} &&  ${NODE_EXEC}; 
run_posts:
	cd ${POSTS_DIR} && ${NODE_EXEC}; 
run_query:
	cd ${QUERY_DIR} && ${NODE_EXEC}; 
